name: Deploy Assets to WordPress.org

on:
  push:
    branches:
      - main  # or master, depending on your primary branch
    paths:
      - '.wordpress-org/**'
  workflow_dispatch:

jobs:
  assets:
    name: Update Plugin Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: WordPress.org Asset Deploy
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ secrets.PLUGIN_SLUG }}
          # Optional: If you want to ensure it strictly ignores any other unintentional code changes
          IGNORE_OTHER_FILES: true
